import fs from 'fs';
const html=fs.readFileSync('index.html','utf8');
const app=fs.readFileSync('app.js','utf8');
const css=fs.readFileSync('styles.css','utf8');
const routes=fs.readFileSync('data/routes.js','utf8');
const required=['anchorRouteToTrip','optimizeCoreOrder','coreEntry','coreExit','baseStart','baseFinish','Google route preview','Download GPX','prefetchTripMedia','directMediaCandidates','curvescout-helmet-visual.png'];
const hay=html+'\n'+app+'\n'+css+'\n'+routes;
const missing=required.filter(x=>!hay.includes(x));
if(missing.length) throw new Error('missing deployment capability markers: '+missing.join(', '));
if(/Google after lock|Google route preview loading/.test(app+html)) throw new Error('stale Google held-back copy still visible');
if(!html.includes('curvescout-mark-transparent.png')) throw new Error('red tight helmet logo not used in header');
if(!css.includes('curvescout-helmet-visual.png')) throw new Error('red watermark styling missing');
if(!app.includes('fetchpriority') || !app.includes('loading=\'eager\'') && !app.includes('loading','eager')) throw new Error('hero media loading priority missing');
if(!app.includes('href="${g.href}"')) throw new Error('Google pills are not anchors');
if(!app.includes('waypointAdvice(w,r,i)')) throw new Error('expanded waypoint advice is not used in roadbook');
if(!app.includes('function splitMediaList')) throw new Error('splitMediaList missing: image/search runtime would crash');
if(!app.includes('async function currentLocation()')) throw new Error('current-location handler missing');
if(!css.includes('background:transparent!important') || !css.includes('box-shadow:none!important')) throw new Error('helmet logo still has a visible box/background');
if(css.includes('Google after lock')) throw new Error('stale Google-lock copy in CSS');
console.log('CurveScout.com v1.4.5 deployment audit ok');
